name: Build and Push All Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - name: Generate Docker matrix
        id: set-matrix
        run: |
          # Store the generated JSON in a temporary variable
          # We use 'matrix_json' here to avoid conflict with the output variable name 'matrix'
          matrix_json=$(find docker -mindepth 3 -maxdepth 3 -name Dockerfile | \
            sed -E 's|docker/(.*)/([^/]+)/Dockerfile|{"component":"\1","role":"\2"}|' | \
            jq -s .)

          # Set the output variable using the multi-line string syntax (heredoc)
          # This is crucial for correctly passing JSON arrays to outputs
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$matrix_json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Print the generated matrix to the workflow logs for debugging
          echo "Generated Matrix: $matrix_json"

  build-and-push:
    needs: generate-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ matrix.component }}/${{ matrix.role }}
          file: ./docker/${{ matrix.component }}/${{ matrix.role }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/devbase-${{ matrix.component }}-${{ matrix.role }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/devbase-${{ matrix.component }}-${{ matrix.role }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/devbase-${{ matrix.component }}-${{ matrix.role }}:${{ github.run_number }}
